[build]
  command = "rm -rf node_modules && pnpm install --no-frozen-lockfile && pnpm run build"
  publish = ".netlify/functions-internal"

[dev]
  command = "pnpm run dev"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/sveltekit-render/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  PUBLIC_BASE_URL = "https://hookah-test.netlify.app" 