[build]
  command = "pnpm config set unsafe-perm true && pnpm config set node-linker hoisted && pnpm run build"
  publish = ".netlify/functions-internal"

[dev]
  command = "pnpm run dev"
  port = 5173

[build.environment]
  NPM_FLAGS = "--unsafe-perm=true" 