[build]
  command = "rm -rf node_modules && pnpm install --no-frozen-lockfile && pnpm run build"
  publish = ".netlify/functions-internal"

[dev]
  command = "pnpm run dev"
  port = 5173

[build.environment]
  NODE_VERSION = "18"
  PUBLIC_BASE_URL = "https://hookah-test.netlify.app" 