[build]
  command = "pnpm run build"
  publish = ".netlify/server"
  functions = "netlify/functions"

[dev]
  command = "pnpm run dev"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 