[build]
  command = "pnpm run build"
  publish = "build"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[dev]
  command = "pnpm run dev"
  port = 5173

[functions]
  included_files = ["!node_modules/**, !.git/**"]
  external_node_modules = ["@sveltejs/kit", "svelte", "svelte/internal"] 